version: "3.4"
services:
  react-nx-api:
    container_name: react-nx-api
    build:
      context: ./react-nx-api/
      target: react-nx-api
    networks:
      tymg:
  react-nx-ui:
    container_name: react-nx-ui
    build:
      context: ./react-nx-api/
      target: react-nx-ui
    ports:
      - 80:80
      - 3333:3333
    networks:
      tymg:
networks:
  tymg:
