FROM node:12 AS react-nx-base
WORKDIR /app
COPY . .
RUN npm ci -S
RUN npm run build -S
RUN npm prune --production -S

FROM nginx:alpine AS react-nx-ui
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=react-nx-base /app/dist/apps/react-nx-docker .

FROM node:12 AS react-nx-api
EXPOSE 3333
WORKDIR /app
COPY --from=react-nx-base /app/node_modules /app/node_modules
COPY --from=react-nx-base /app/dist/apps/api .
CMD ["node", "main.js"]